import Head from 'next/head'
import ProductCard from '@/components/ProductsCards'

export default function Home() {
  return (
    <>
      <Head>
        <title>NextJS - Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{padding:"0px 30px"}} className='Home'>
        <h1 style={{ textAlign: "Center", margin: "60px auto 30px auto",fontWeight:"600" }}>Products</h1>
        <ProductCard />
      </div>
    </>
  )
}
